---
- hosts: all
  become: yes
  vars:
      db_user: dbusername
      db_name: dbname
      db_password: dbpassword
      postgresql_version: 12
      devices: /dev/sdb1
      device_name: /dev/sdb
      uuid: cd1f62d7-b546-4f3f-b329-d0fa8062424a
  
  tasks:
      #- name: partition new disk
      #  shell: echo -e "n\np\n1\n\n\nw" | sudo fdisk /dev/sdb
      #  args:
      #   executable: /bin/bash

      - name: Create a new ext4 primary partition
        community.general.parted:
         device: /dev/sdb
         number: 1
         state: present
         fs_type: ext4      

      - name: Create a ext4 filesystem on /dev/sdb1
        community.general.filesystem:
         fstype: ext4
         dev: /dev/sdb1

      - name: Creates directory to postgresql
        file:
          path:  /var/lib/postgresql
          state: directory
          #owner: postgres
          #group: postgres
          mode:  777       

#      - name: Mount a device by label
#        mount:   
#         src:  'UUID={{ uuid }}'
#         path: /var/lib/postgresql/
#         fstype: ext4
#         state: present


#      - name: add /var/lib/postgresql entry to /etc/fstab
#        mount:
#         path: /var/lib/postgresql/
#         src: 'UUID={{ uuid }}'
#         fstype: ext4
#         opts: defaults,auto,noatime,_netdev
#         dump: '0'
#         state: mounted


      - name:  Mount command
        shell: mount UUID=$(blkid /dev/sda1 -sUUID -ovalue) /var/lib/postgresql/
        args:
         executable: /bin/bash      

      - name:  Mount -a command
        shell: sudo mount -a
        args:
         executable: /bin/bash      