---
- hosts: all
  become: yes
  vars:
    db_user: dbusername
    db_name: dbname
    db_name2: postgres
    db_name3: test1
    db_password: dbpassword
    postgresql_version: 15

  tasks:
    - name: Install packages git
      apt: name={{ item }} update_cache=true state=latest
      with_items:
        - git
        - net-tools
        - neofetch
        - net-tools
        - traceroute
        - nmap
        - gcc
        - postfix
        - mailutils
