---
- hosts: all
  become: yes
  vars:
      db_user: dbusername
      db_name: dvdrental
      db_name2: postgres      
      db_name3: test1      
      db_password: dbpassword
      postgresql_version: 14

  tasks:


      - name: Create the database specified in vars
        become: true
        become_user: postgres
        postgresql_db: name={{ db_name }}
            template='template0'
            state=present


      - name: Install unzip  
        shell: apt install -y unzip
        args:
         executable: /bin/bash    


#      - name: createdb dvdrental 
#        become: true
#        become_user: postgres      
#        shell: createdb dvdrental 
#        args:
#         executable: /bin/bash    



      - name: pg_restore dvdrental.zip 
        become: true
        become_user: postgres      
        shell: pg_restore -U postgres -d dvdrental  /tmp/dvdrental.tar 
        args:
         executable: /bin/bash    




## REFERENCES: 
## https://www.postgresqltutorial.com/load-postgresql-sample-database/
## https://www.youtube.com/watch?v=ctESJSfgkBg&t=57s
## https://www.postgresqltutorial.com/postgresql-sample-database/

