---
- hosts: all
  become: yes
  vars:
    db_user: dbusername
    db_name: dbname
    db_name2: mockaroo
    db_name3: test1
    db_password: dbpassword
    postgresql_version: 15

  tasks:
    - name: Ansible copy file MOCK_DATA.sql to remote server
      copy:
        owner: postgres
        group: postgres
        src: MOCK_DATA.sql
        dest: /var/lib/postgresql/scripts

    - name: Ensure the PostgreSQL service is running
      service: name=postgresql state=started enabled=yes

    - name: Create the database specified in vars
      become: true
      become_user: postgres
      postgresql_db: name={{ db_name2 }}
        template='template0'
        state=present

    - name: Ensure user has access to the new database and exec .sql
      become: true
      become_user: postgres
      shell: psql {{ db_name2 }} < /var/lib/postgresql/scripts/MOCK_DATA.sql

    - name: Restart postgresql
      service: name=postgresql state=restarted
