---
- hosts: all
  become: yes
  vars:
    db_user: dbusername
    db_name: dbname
    db_name2: postgres
    db_name3: test1
    db_password: dbpassword
    postgresql_version: 15

  tasks:
    - name: Recursively change ownership of a directory /postgresql/backups/
      ansible.builtin.file:
        path: /postgresql/backups/
        state: directory
        recurse: yes
        owner: postgres
        group: postgres

    - name: Recursively change ownership of a directory /postgresql/
      ansible.builtin.file:
        path: /postgresql/
        state: directory
        recurse: yes
        owner: postgres
        group: postgres
