---
- hosts: all
  become: yes
  vars:
    db_user: dbusername
    db_name: dbname
    db_name2: postgres
    db_name3: test1
    db_password: dbpassword
    postgresql_version: 15

  tasks:
    #      - name: Stop postgresql service
    #        shell: service postgresql stop
    #        args:
    #         executable: /bin/bash

    - name: Ansible copy file pgbackrest-restore.sh to remote server
      copy:
        owner: postgres
        group: postgres
        mode: 0777
        src: pgbackrest-restore.sh
        dest: /var/lib/postgresql/scripts

    - name: Cronjob Entry pgbackrest-restore.sh scripts
      cron:
        name: "### execute pgbackrest-restore.sh to RESTORE"
        user: postgres
        minute: "0"
        hour: "*04"
        day: "*"
        month: "*"
        weekday: "1-5"
        job: /var/lib/postgresql/scripts/pgbackrest-restore.sh
