---
- hosts: all
  become: yes
  vars:
    db_user: dbusername
    db_name: dbname
    db_name2: postgres
    db_name3: test1
    db_password: dbpassword
    postgresql_version: 15

  tasks:
    #   - name: Creates directory to scripts
    #     file:
    #       path: /var/lib/postgresql/scripts
    #       state: directory
    #       owner: postgres
    #       group: postgres
    #       mode: 0777

    - name: Ensure the PostgreSQL service is running
      service: name=postgresql state=started enabled=yes

    - name: Restart the PostgreSQL service
      service: name=postgresql state=restarted

    - name: Create the database pgbench
      become: true
      become_user: postgres
      postgresql_db: name=pgbench
        template='template0'
        state=present

    - name: Command pgbench
      become: true
      become_user: postgres
      shell: /lib/postgresql/15/bin/pgbench -i pgbench
      args:
        executable: /bin/bash

    - name: Cronjob Entry pgbench scripts
      cron:
        name: "### execute pgbench scripts"
        user: postgres
        minute: "*/10"
        hour: "*"
        day: "*"
        month: "*"
        weekday: "*"
        job: /lib/postgresql/15/bin/pgbench -c 5 -j 2 -t 10 pgbench

    - name: Cronjob Entry high benchmark scripts
      cron:
        name: "### execute high benchmark scripts"
        user: postgres
        minute: "10"
        hour: "*"
        day: "*"
        month: "*"
        weekday: "*"
        job: /lib/postgresql/15/bin/pgbench -c 20 -j 2 -t 100 pgbench
