---
- name: user module demo
  hosts: all
  become: true
  vars:
    myuser: "ubuntu"
    mypassword: "qaz*()Q"
  tasks:
    - name: change password
      ansible.builtin.user:
        name: "{{ myuser }}"
        state: present
        password: "{{ mypassword | password_hash('sha512') }}"