--https://www.mockaroo.com/


create table MOCK_DATA (
	id INT,
	first_name VARCHAR(50),
	last_name VARCHAR(50),
	email VARCHAR(50),
	gender VARCHAR(50),
	ip_address VARCHAR(20),
	drug_company VARCHAR(50),
	stock_industry VARCHAR(50),
	timee VARCHAR(50)
);
insert into MOCK_DATA (id, first_name, last_name, email, gender, ip_address, drug_company, stock_industry, timee) values (1, 'Bartholomeus', 'Brace', 'bbrace0@ameblo.jp', 'Male', '24.241.95.243', 'Aplicare, Inc.', 'Advertising', '10:55 AM');
insert into MOCK_DATA (id, first_name, last_name, email, gender, ip_address, drug_company, stock_industry, timee) values (2, 'Jeremy', 'Hurry', 'jhurry1@earthlink.net', 'Male', '180.17.151.210', 'Lake Erie Medical DBA Quality Care Products LLC', 'Savings Institutions', '8:46 PM');
insert into MOCK_DATA (id, first_name, last_name, email, gender, ip_address, drug_company, stock_industry, timee) values (3, 'Janot', 'Zorzoni', 'jzorzoni2@netlog.com', 'Female', '117.123.240.160', 'Sagent Pharmaceuticals', 'Property-Casualty Insurers', '6:48 AM');
insert into MOCK_DATA (id, first_name, last_name, email, gender, ip_address, drug_company, stock_industry, timee) values (4, 'Sara', 'Hender', 'shender3@bloglines.com', 'Female', '4.216.120.38', 'MD Solar Sciences', 'Business Services', '7:51 AM');
insert into MOCK_DATA (id, first_name, last_name, email, gender, ip_address, drug_company, stock_industry, timee) values (5, 'Dorey', 'Lyddon', 'dlyddon4@google.es', 'Male', '100.44.61.72', 'Prime Packaging, Inc.', 'n/a', '10:16 AM');
insert into MOCK_DATA (id, first_name, last_name, email, gender, ip_address, drug_company, stock_industry, timee) values (6, 'Alyss', 'Highnam', 'ahighnam5@mashable.com', 'Female', '90.59.65.204', 'Teva Pharmaceuticals USA Inc', 'n/a', '12:40 PM');
insert into MOCK_DATA (id, first_name, last_name, email, gender, ip_address, drug_company, stock_industry, timee) values (7, 'Robby', 'Scrivens', 'rscrivens6@skype.com', 'Male', '174.195.154.86', 'QUALITY CHOICE (Chain Drug Marketing Association)', 'Computer Software: Prepackaged Software', '10:57 AM');
insert into MOCK_DATA (id, first_name, last_name, email, gender, ip_address, drug_company, stock_industry, timee) values (8, 'Kanya', 'Ludy', 'kludy7@miibeian.gov.cn', 'Genderfluid', '248.187.36.103', 'Nelco Laboratories, Inc.', 'Major Chemicals', '3:55 PM');
insert into MOCK_DATA (id, first_name, last_name, email, gender, ip_address, drug_company, stock_industry, timee) values (9, 'Massimiliano', 'O''Rudden', 'morudden8@craigslist.org', 'Male', '58.254.96.100', 'GW Laboratories, Inc', 'Building operators', '12:33 PM');
insert into MOCK_DATA (id, first_name, last_name, email, gender, ip_address, drug_company, stock_industry, timee) values (10, 'Pernell', 'Backson', 'pbackson9@dion.ne.jp', 'Genderqueer', '118.250.201.125', 'Aphena Pharma Solutions - Tennessee, LLC', 'n/a', '4:23 AM');
insert into MOCK_DATA (id, first_name, last_name, email, gender, ip_address, drug_company, stock_industry, timee) values (11, 'Dionysus', 'Daborne', 'ddabornea@discuz.net', 'Male', '171.61.165.186', 'Strides Arcolab Limited', 'Specialty Chemicals', '1:03 PM');
insert into MOCK_DATA (id, first_name, last_name, email, gender, ip_address, drug_company, stock_industry, timee) values (12, 'Clarita', 'Boanas', 'cboanasb@123-reg.co.uk', 'Female', '60.148.7.109', 'Safeway, Inc.', 'Consumer Electronics/Appliances', '2:15 AM');
insert into MOCK_DATA (id, first_name, last_name, email, gender, ip_address, drug_company, stock_industry, timee) values (13, 'Ted', 'Waddilow', 'twaddilowc@auda.org.au', 'Female', '76.185.57.123', 'STAT RX USA LLC', 'Major Banks', '3:58 AM');
insert into MOCK_DATA (id, first_name, last_name, email, gender, ip_address, drug_company, stock_industry, timee) values (14, 'Anne-corinne', 'Sherr', 'asherrd@cam.ac.uk', 'Female', '115.190.160.209', 'Health-Tech, Inc.', 'n/a', '12:10 PM');
insert into MOCK_DATA (id, first_name, last_name, email, gender, ip_address, drug_company, stock_industry, timee) values (15, 'Izaak', 'Butterwick', 'ibutterwicke@google.es', 'Male', '184.103.104.81', 'Warner Chilcott Pharmaceuticals Inc.', 'n/a', '1:51 PM');
insert into MOCK_DATA (id, first_name, last_name, email, gender, ip_address, drug_company, stock_industry, timee) values (16, 'Donavon', 'Burnyate', 'dburnyatef@harvard.edu', 'Male', '112.13.141.190', 'Uriel Pharmacy Inc.', 'Business Services', '12:21 AM');
insert into MOCK_DATA (id, first_name, last_name, email, gender, ip_address, drug_company, stock_industry, timee) values (17, 'Helenelizabeth', 'Antonomoli', 'hantonomolig@seesaa.net', 'Female', '230.229.206.140', 'UNITED EXCHANGE CORP.', 'Savings Institutions', '4:09 AM');
insert into MOCK_DATA (id, first_name, last_name, email, gender, ip_address, drug_company, stock_industry, timee) values (18, 'Jase', 'Sparkes', 'jsparkesh@cisco.com', 'Male', '182.42.136.205', 'Meda Pharmaceuticals Inc.', 'n/a', '7:55 PM');
insert into MOCK_DATA (id, first_name, last_name, email, gender, ip_address, drug_company, stock_industry, timee) values (19, 'Donetta', 'Pere', 'dperei@huffingtonpost.com', 'Female', '61.236.203.100', 'Merle Norman Cosmetics, Inc.', 'Medical/Dental Instruments', '12:07 PM');
insert into MOCK_DATA (id, first_name, last_name, email, gender, ip_address, drug_company, stock_industry, timee) values (20, 'Wylie', 'MacAlinden', 'wmacalindenj@wikispaces.com', 'Male', '7.158.96.184', 'Amneal Pharmaceuticals of New York, LLC', 'Ophthalmic Goods', '4:03 PM');
insert into MOCK_DATA (id, first_name, last_name, email, gender, ip_address, drug_company, stock_industry, timee) values (21, 'Patrizio', 'Dyers', 'pdyersk@cnn.com', 'Male', '11.95.40.52', 'Amerisource Bergen', 'n/a', '6:54 PM');
insert into MOCK_DATA (id, first_name, last_name, email, gender, ip_address, drug_company, stock_industry, timee) values (22, 'Lynde', 'Brugsma', 'lbrugsmal@xing.com', 'Female', '87.213.75.249', 'Actavis Pharma Manufacturing Pvt Ltd. (SOD)', 'Real Estate Investment Trusts', '11:13 AM');
insert into MOCK_DATA (id, first_name, last_name, email, gender, ip_address, drug_company, stock_industry, timee) values (23, 'Deloria', 'Bubbear', 'dbubbearm@geocities.jp', 'Female', '124.102.91.193', 'REMEDYREPACK INC.', 'n/a', '2:52 AM');
insert into MOCK_DATA (id, first_name, last_name, email, gender, ip_address, drug_company, stock_industry, timee) values (24, 'Codie', 'Worssam', 'cworssamn@diigo.com', 'Male', '136.107.53.237', 'Wal-Mart Stores Inc', 'Restaurants', '10:22 AM');
insert into MOCK_DATA (id, first_name, last_name, email, gender, ip_address, drug_company, stock_industry, timee) values (25, 'Salaidh', 'Gittoes', 'sgittoeso@independent.co.uk', 'Female', '248.98.248.75', 'Laboratoires Clarins S.A.', 'Computer Software: Programming, Data Processing', '1:43 AM');
insert into MOCK_DATA (id, first_name, last_name, email, gender, ip_address, drug_company, stock_industry, timee) values (26, 'Norton', 'Farrants', 'nfarrantsp@admin.ch', 'Male', '254.218.60.27', 'Kremers Urban Pharmaceuticals Inc', 'n/a', '2:08 AM');
insert into MOCK_DATA (id, first_name, last_name, email, gender, ip_address, drug_company, stock_industry, timee) values (27, 'Selie', 'Ivanyushkin', 'sivanyushkinq@mysql.com', 'Female', '208.46.246.112', 'H E B', 'n/a', '6:57 AM');
insert into MOCK_DATA (id, first_name, last_name, email, gender, ip_address, drug_company, stock_industry, timee) values (28, 'Griffy', 'Joynson', 'gjoynsonr@walmart.com', 'Male', '104.220.207.107', 'Ventura International LTD.', 'Homebuilding', '12:24 PM');
insert into MOCK_DATA (id, first_name, last_name, email, gender, ip_address, drug_company, stock_industry, timee) values (29, 'Maxie', 'Daughtry', 'mdaughtrys@senate.gov', 'Female', '206.122.47.205', 'Meijer Distribution Inc', 'Packaged Foods', '1:19 AM');
insert into MOCK_DATA (id, first_name, last_name, email, gender, ip_address, drug_company, stock_industry, timee) values (30, 'Dedie', 'Coultas', 'dcoultast@posterous.com', 'Female', '254.112.24.107', 'State of Florida DOH Central Pharmacy', 'Military/Government/Technical', '4:13 AM');
insert into MOCK_DATA (id, first_name, last_name, email, gender, ip_address, drug_company, stock_industry, timee) values (31, 'Bondon', 'Ferronet', 'bferronetu@mozilla.org', 'Male', '117.134.178.157', 'THEFACESHOP CO., LTD', 'Auto Parts:O.E.M.', '11:45 PM');
insert into MOCK_DATA (id, first_name, last_name, email, gender, ip_address, drug_company, stock_industry, timee) values (32, 'Aigneis', 'Ramsell', 'aramsellv@arstechnica.com', 'Female', '85.82.89.165', 'Procter & Gamble Manufacturing Company', 'Major Pharmaceuticals', '7:11 PM');
insert into MOCK_DATA (id, first_name, last_name, email, gender, ip_address, drug_company, stock_industry, timee) values (33, 'Mozelle', 'Foard', 'mfoardw@linkedin.com', 'Female', '170.135.129.112', 'International Nature Nutraceuticals', 'Home Furnishings', '11:35 PM');
insert into MOCK_DATA (id, first_name, last_name, email, gender, ip_address, drug_company, stock_industry, timee) values (34, 'Mersey', 'Kort', 'mkortx@examiner.com', 'Female', '10.100.42.19', 'Physicians Total Care, Inc.', 'n/a', '10:37 PM');
insert into MOCK_DATA (id, first_name, last_name, email, gender, ip_address, drug_company, stock_industry, timee) values (35, 'Deedee', 'Paget', 'dpagety@intel.com', 'Female', '77.2.239.229', 'Newton Laboratories, Inc.', 'Major Banks', '12:30 AM');
insert into MOCK_DATA (id, first_name, last_name, email, gender, ip_address, drug_company, stock_industry, timee) values (36, 'Akim', 'MacCawley', 'amaccawleyz@163.com', 'Male', '156.201.58.119', 'GlaxoSmithKline LLC', 'Major Banks', '8:29 PM');
insert into MOCK_DATA (id, first_name, last_name, email, gender, ip_address, drug_company, stock_industry, timee) values (37, 'Elinor', 'Zipsell', 'ezipsell10@spotify.com', 'Female', '21.187.181.211', 'REMEDYREPACK INC.', 'Real Estate Investment Trusts', '8:05 AM');
insert into MOCK_DATA (id, first_name, last_name, email, gender, ip_address, drug_company, stock_industry, timee) values (38, 'Kendal', 'Appleyard', 'kappleyard11@simplemachines.org', 'Male', '73.182.69.157', 'Lake Erie Medical & Surgical Supply DBA Quality Care Products LLC', 'Major Banks', '9:18 PM');
insert into MOCK_DATA (id, first_name, last_name, email, gender, ip_address, drug_company, stock_industry, timee) values (39, 'Morie', 'Drabble', 'mdrabble12@free.fr', 'Male', '156.199.45.68', 'Shopko Stores Operating Co., LLC', 'Real Estate', '8:49 AM');
insert into MOCK_DATA (id, first_name, last_name, email, gender, ip_address, drug_company, stock_industry, timee) values (40, 'Lynna', 'Quimby', 'lquimby13@aboutads.info', 'Bigender', '243.131.77.34', 'Keltman Pharmaceuticals Inc.', 'Major Banks', '11:08 AM');
insert into MOCK_DATA (id, first_name, last_name, email, gender, ip_address, drug_company, stock_industry, timee) values (41, 'Elisa', 'Amoss', 'eamoss14@nationalgeographic.com', 'Female', '220.118.159.195', 'REMEDYREPACK INC.', 'Medical Electronics', '1:11 AM');
insert into MOCK_DATA (id, first_name, last_name, email, gender, ip_address, drug_company, stock_industry, timee) values (42, 'Webster', 'Pummell', 'wpummell15@goo.gl', 'Male', '49.238.61.12', 'Care One (American Sales Company)', 'Major Chemicals', '10:23 PM');
insert into MOCK_DATA (id, first_name, last_name, email, gender, ip_address, drug_company, stock_industry, timee) values (43, 'Ollie', 'Mardle', 'omardle16@blogspot.com', 'Male', '2.2.91.243', 'Transdermal Corp', 'Major Banks', '3:10 AM');
insert into MOCK_DATA (id, first_name, last_name, email, gender, ip_address, drug_company, stock_industry, timee) values (44, 'Gregorius', 'Cast', 'gcast17@ihg.com', 'Male', '135.124.90.71', 'McNeil Consumer Healthcare Div. McNeil-PPC, Inc', 'Computer Software: Prepackaged Software', '12:45 PM');
insert into MOCK_DATA (id, first_name, last_name, email, gender, ip_address, drug_company, stock_industry, timee) values (45, 'Brander', 'Fendlen', 'bfendlen18@cmu.edu', 'Male', '53.198.107.84', 'ALK-Abello, Inc.', 'Commercial Banks', '9:35 AM');
insert into MOCK_DATA (id, first_name, last_name, email, gender, ip_address, drug_company, stock_industry, timee) values (46, 'Lois', 'Duchan', 'lduchan19@nbcnews.com', 'Female', '93.240.44.186', 'Nelco Laboratories, Inc.', 'n/a', '8:58 AM');
insert into MOCK_DATA (id, first_name, last_name, email, gender, ip_address, drug_company, stock_industry, timee) values (47, 'Kalina', 'Facer', 'kfacer1a@salon.com', 'Female', '6.145.44.36', 'Safeway', 'Oil/Gas Transmission', '8:01 AM');
insert into MOCK_DATA (id, first_name, last_name, email, gender, ip_address, drug_company, stock_industry, timee) values (48, 'Haroun', 'Adcock', 'hadcock1b@google.nl', 'Male', '186.6.89.72', 'McKesson', 'Biotechnology: In Vitro & In Vivo Diagnostic Substances', '12:10 AM');
insert into MOCK_DATA (id, first_name, last_name, email, gender, ip_address, drug_company, stock_industry, timee) values (49, 'Wang', 'Fisbburne', 'wfisbburne1c@ning.com', 'Genderqueer', '151.131.5.79', 'H E B', 'Investment Bankers/Brokers/Service', '3:10 PM');
insert into MOCK_DATA (id, first_name, last_name, email, gender, ip_address, drug_company, stock_industry, timee) values (50, 'Gothart', 'Teare', 'gteare1d@mozilla.com', 'Male', '53.241.71.36', 'Deseret Biologicals, Inc.', 'Telecommunications Equipment', '7:08 AM');
insert into MOCK_DATA (id, first_name, last_name, email, gender, ip_address, drug_company, stock_industry, timee) values (51, 'Aindrea', 'Hemphrey', 'ahemphrey1e@washington.edu', 'Female', '8.121.172.112', 'Western Family Foods, Inc.', 'Real Estate', '5:07 AM');
insert into MOCK_DATA (id, first_name, last_name, email, gender, ip_address, drug_company, stock_industry, timee) values (52, 'Arleyne', 'Pardew', 'apardew1f@cpanel.net', 'Female', '66.110.209.242', 'Bryant Ranch Prepack', 'Industrial Machinery/Components', '4:58 PM');
insert into MOCK_DATA (id, first_name, last_name, email, gender, ip_address, drug_company, stock_industry, timee) values (53, 'Loraine', 'Wasbrough', 'lwasbrough1g@fastcompany.com', 'Female', '1.253.246.1', 'TRP Company', 'n/a', '6:01 AM');
insert into MOCK_DATA (id, first_name, last_name, email, gender, ip_address, drug_company, stock_industry, timee) values (54, 'Larine', 'Baber', 'lbaber1h@tuttocitta.it', 'Female', '28.160.67.68', 'Nelco Laboratories, Inc.', 'Major Pharmaceuticals', '11:07 AM');
insert into MOCK_DATA (id, first_name, last_name, email, gender, ip_address, drug_company, stock_industry, timee) values (55, 'Marnia', 'Derrett', 'mderrett1i@bbb.org', 'Female', '13.170.121.203', 'Select Corporation', 'Military/Government/Technical', '11:52 PM');
insert into MOCK_DATA (id, first_name, last_name, email, gender, ip_address, drug_company, stock_industry, timee) values (56, 'Hermia', 'Waadenburg', 'hwaadenburg1j@hatena.ne.jp', 'Female', '10.67.36.218', 'AvKARE, Inc.', 'Real Estate Investment Trusts', '8:58 AM');
insert into MOCK_DATA (id, first_name, last_name, email, gender, ip_address, drug_company, stock_industry, timee) values (57, 'Valry', 'Gallego', 'vgallego1k@nytimes.com', 'Genderqueer', '174.225.129.28', 'Apotheca Company', 'Computer Software: Prepackaged Software', '8:52 AM');
insert into MOCK_DATA (id, first_name, last_name, email, gender, ip_address, drug_company, stock_industry, timee) values (58, 'Keen', 'Ofen', 'kofen1l@chronoengine.com', 'Bigender', '191.42.87.106', 'Bryant Ranch Prepack', 'Computer Software: Prepackaged Software', '11:53 AM');
insert into MOCK_DATA (id, first_name, last_name, email, gender, ip_address, drug_company, stock_industry, timee) values (59, 'Aubrette', 'Taysbil', 'ataysbil1m@4shared.com', 'Female', '247.89.149.216', 'ALK-Abello, Inc.', 'Real Estate Investment Trusts', '2:20 PM');
insert into MOCK_DATA (id, first_name, last_name, email, gender, ip_address, drug_company, stock_industry, timee) values (60, 'Keefer', 'Legon', 'klegon1n@theguardian.com', 'Male', '104.211.113.226', 'Kroger Company', 'Semiconductors', '12:37 AM');
insert into MOCK_DATA (id, first_name, last_name, email, gender, ip_address, drug_company, stock_industry, timee) values (61, 'Anson', 'Castilljo', 'acastilljo1o@sitemeter.com', 'Male', '193.202.136.2', 'Physicians Total Care, Inc.', 'Major Pharmaceuticals', '11:56 AM');
insert into MOCK_DATA (id, first_name, last_name, email, gender, ip_address, drug_company, stock_industry, timee) values (62, 'Shurlocke', 'Sushams', 'ssushams1p@mac.com', 'Male', '123.42.218.209', 'Zydus Pharmaceuticals (USA) Inc.', 'n/a', '8:22 PM');
insert into MOCK_DATA (id, first_name, last_name, email, gender, ip_address, drug_company, stock_industry, timee) values (63, 'Ewell', 'Aickin', 'eaickin1q@sitemeter.com', 'Male', '34.123.10.184', 'Novartis Pharmaceuticals Corporation', 'Business Services', '1:45 AM');
insert into MOCK_DATA (id, first_name, last_name, email, gender, ip_address, drug_company, stock_industry, timee) values (64, 'Alyson', 'Adamczewski', 'aadamczewski1r@taobao.com', 'Female', '69.107.237.191', 'Aton Pharma, Inc.', 'Electrical Products', '11:41 AM');
insert into MOCK_DATA (id, first_name, last_name, email, gender, ip_address, drug_company, stock_industry, timee) values (65, 'Emiline', 'Shepton', 'eshepton1s@artisteer.com', 'Female', '186.209.40.199', 'PD-Rx Pharmaceuticals, Inc.', 'Major Pharmaceuticals', '3:57 AM');
insert into MOCK_DATA (id, first_name, last_name, email, gender, ip_address, drug_company, stock_industry, timee) values (66, 'Jemie', 'Klimentov', 'jklimentov1t@liveinternet.ru', 'Female', '20.90.29.117', 'CVS Pharmacy, Inc', 'n/a', '2:26 PM');
insert into MOCK_DATA (id, first_name, last_name, email, gender, ip_address, drug_company, stock_industry, timee) values (67, 'Salomo', 'Summerfield', 'ssummerfield1u@globo.com', 'Male', '2.230.199.200', 'Pfizer Laboratories Div Pfizer Inc', 'Oil & Gas Production', '9:53 AM');
insert into MOCK_DATA (id, first_name, last_name, email, gender, ip_address, drug_company, stock_industry, timee) values (68, 'Claiborn', 'Habben', 'chabben1v@shareasale.com', 'Male', '73.131.211.124', 'Bausch & Lomb Incoporated', 'Investment Bankers/Brokers/Service', '9:19 AM');
insert into MOCK_DATA (id, first_name, last_name, email, gender, ip_address, drug_company, stock_industry, timee) values (69, 'Faulkner', 'Mathy', 'fmathy1w@google.fr', 'Bigender', '102.238.39.155', 'CVS Pharmacy', 'Oil & Gas Production', '12:01 PM');
insert into MOCK_DATA (id, first_name, last_name, email, gender, ip_address, drug_company, stock_industry, timee) values (70, 'Kimmie', 'McLeoid', 'kmcleoid1x@bbb.org', 'Agender', '112.47.222.188', 'Physicians Total Care, Inc.', 'Office Equipment/Supplies/Services', '1:28 PM');
insert into MOCK_DATA (id, first_name, last_name, email, gender, ip_address, drug_company, stock_industry, timee) values (71, 'Elfie', 'Goldring', 'egoldring1y@slashdot.org', 'Female', '85.100.87.81', 'Rubbermaid Commercial Products LLC', 'n/a', '8:52 PM');
insert into MOCK_DATA (id, first_name, last_name, email, gender, ip_address, drug_company, stock_industry, timee) values (72, 'Mace', 'Jacobbe', 'mjacobbe1z@mapquest.com', 'Male', '48.214.121.21', 'New World Imports, Inc.', 'Fluid Controls', '1:56 AM');
insert into MOCK_DATA (id, first_name, last_name, email, gender, ip_address, drug_company, stock_industry, timee) values (73, 'Ambrosius', 'MacAndrew', 'amacandrew20@sourceforge.net', 'Male', '192.150.250.118', 'AmerisourceBergen (Good Neighbor Pharmacy) 46122', 'Forest Products', '9:59 PM');
insert into MOCK_DATA (id, first_name, last_name, email, gender, ip_address, drug_company, stock_industry, timee) values (74, 'Jarid', 'Elfitt', 'jelfitt21@nhs.uk', 'Male', '3.198.115.74', 'Endo Pharmaceuticals Solutions Inc.', 'n/a', '10:09 PM');
insert into MOCK_DATA (id, first_name, last_name, email, gender, ip_address, drug_company, stock_industry, timee) values (75, 'Francene', 'Warboy', 'fwarboy22@ustream.tv', 'Female', '221.190.91.185', 'Swedish Orphan Biovitrum AB (publ)', 'Business Services', '7:03 AM');
insert into MOCK_DATA (id, first_name, last_name, email, gender, ip_address, drug_company, stock_industry, timee) values (76, 'Annelise', 'Lusher', 'alusher23@g.co', 'Female', '153.170.130.206', 'Rite Aid Corporation', 'n/a', '3:08 AM');
insert into MOCK_DATA (id, first_name, last_name, email, gender, ip_address, drug_company, stock_industry, timee) values (77, 'Ginevra', 'Moxon', 'gmoxon24@usnews.com', 'Female', '183.17.18.145', 'Janssen Pharmaceutical, Inc.', 'Major Pharmaceuticals', '6:51 PM');
insert into MOCK_DATA (id, first_name, last_name, email, gender, ip_address, drug_company, stock_industry, timee) values (78, 'Margy', 'Bardsley', 'mbardsley25@toplist.cz', 'Female', '49.65.92.183', 'Parfums Christian Dior', 'Major Banks', '4:24 PM');
insert into MOCK_DATA (id, first_name, last_name, email, gender, ip_address, drug_company, stock_industry, timee) values (79, 'Shermie', 'Darlasson', 'sdarlasson26@economist.com', 'Male', '59.33.90.178', 'Your Military Exchange', 'n/a', '8:01 PM');
insert into MOCK_DATA (id, first_name, last_name, email, gender, ip_address, drug_company, stock_industry, timee) values (80, 'Neron', 'Pettit', 'npettit27@washingtonpost.com', 'Male', '231.198.41.150', 'Nelco Laboratories, Inc.', 'Major Pharmaceuticals', '10:10 PM');
insert into MOCK_DATA (id, first_name, last_name, email, gender, ip_address, drug_company, stock_industry, timee) values (81, 'Shelby', 'Lotte', 'slotte28@freewebs.com', 'Male', '159.238.9.7', 'H2O Plus', 'Industrial Machinery/Components', '10:34 PM');
insert into MOCK_DATA (id, first_name, last_name, email, gender, ip_address, drug_company, stock_industry, timee) values (82, 'Shay', 'Snasdell', 'ssnasdell29@reference.com', 'Male', '114.71.115.214', 'Bioelements', 'Major Chemicals', '2:25 PM');
insert into MOCK_DATA (id, first_name, last_name, email, gender, ip_address, drug_company, stock_industry, timee) values (83, 'Tiebout', 'Solon', 'tsolon2a@google.nl', 'Polygender', '242.123.247.220', 'Delon Laboratories (1990) Ltd', 'Packaged Foods', '3:07 AM');
insert into MOCK_DATA (id, first_name, last_name, email, gender, ip_address, drug_company, stock_industry, timee) values (84, 'Concettina', 'Dockwray', 'cdockwray2b@dmoz.org', 'Female', '36.224.9.52', 'Rebel Distributors Corp', 'Electric Utilities: Central', '10:13 AM');
insert into MOCK_DATA (id, first_name, last_name, email, gender, ip_address, drug_company, stock_industry, timee) values (85, 'Dougy', 'McCome', 'dmccome2c@wp.com', 'Male', '12.249.9.163', 'Hollister-Stier Laboratories LLC', 'Electric Utilities: Central', '12:15 AM');
insert into MOCK_DATA (id, first_name, last_name, email, gender, ip_address, drug_company, stock_industry, timee) values (86, 'Amanda', 'Knudsen', 'aknudsen2d@chicagotribune.com', 'Female', '212.16.126.154', 'Virtus Pharmaceuticals LLC', 'Major Banks', '9:17 AM');
insert into MOCK_DATA (id, first_name, last_name, email, gender, ip_address, drug_company, stock_industry, timee) values (87, 'Gennifer', 'Krammer', 'gkrammer2e@va.gov', 'Female', '176.200.120.173', 'American Sales Company', 'Oil & Gas Production', '5:10 AM');
insert into MOCK_DATA (id, first_name, last_name, email, gender, ip_address, drug_company, stock_industry, timee) values (88, 'Hermine', 'Baptista', 'hbaptista2f@eepurl.com', 'Female', '243.53.75.202', 'Menper Distributors, Inc.', 'Electric Utilities: Central', '5:06 AM');
insert into MOCK_DATA (id, first_name, last_name, email, gender, ip_address, drug_company, stock_industry, timee) values (89, 'Trixy', 'Ashdown', 'tashdown2g@wordpress.com', 'Female', '85.147.36.80', 'Teva Pharmaceuticals USA Inc', 'Major Pharmaceuticals', '1:12 PM');
insert into MOCK_DATA (id, first_name, last_name, email, gender, ip_address, drug_company, stock_industry, timee) values (90, 'Nariko', 'Callinan', 'ncallinan2h@opensource.org', 'Female', '31.98.41.240', 'Shionogi Inc.', 'Other Specialty Stores', '11:11 AM');
insert into MOCK_DATA (id, first_name, last_name, email, gender, ip_address, drug_company, stock_industry, timee) values (91, 'Jock', 'Cooke', 'jcooke2i@sohu.com', 'Male', '123.141.140.142', 'Willspeed Technologies LLC', 'Major Banks', '1:14 PM');
insert into MOCK_DATA (id, first_name, last_name, email, gender, ip_address, drug_company, stock_industry, timee) values (92, 'Marley', 'Pitkeathley', 'mpitkeathley2j@moonfruit.com', 'Female', '193.220.181.122', 'United Exchange Corp', 'Television Services', '2:24 PM');
insert into MOCK_DATA (id, first_name, last_name, email, gender, ip_address, drug_company, stock_industry, timee) values (93, 'Emmit', 'Leggin', 'eleggin2k@si.edu', 'Genderqueer', '41.57.111.181', 'REMEDYREPACK INC.', 'Major Banks', '5:27 AM');
insert into MOCK_DATA (id, first_name, last_name, email, gender, ip_address, drug_company, stock_industry, timee) values (94, 'Casie', 'Brownlow', 'cbrownlow2l@imdb.com', 'Female', '108.209.108.134', 'WALGREEN CO.', 'n/a', '5:51 PM');
insert into MOCK_DATA (id, first_name, last_name, email, gender, ip_address, drug_company, stock_industry, timee) values (95, 'Melvyn', 'Najara', 'mnajara2m@nih.gov', 'Male', '40.51.131.245', 'Apotheca Company', 'Life Insurance', '10:16 PM');
insert into MOCK_DATA (id, first_name, last_name, email, gender, ip_address, drug_company, stock_industry, timee) values (96, 'Shanda', 'Jugging', 'sjugging2n@cafepress.com', 'Female', '46.64.70.210', 'APP Pharmaceuticals, Inc.', 'Industrial Specialties', '12:45 AM');
insert into MOCK_DATA (id, first_name, last_name, email, gender, ip_address, drug_company, stock_industry, timee) values (97, 'Anni', 'Leipoldt', 'aleipoldt2o@alibaba.com', 'Female', '204.216.18.136', 'Safeway, Inc.', 'Industrial Specialties', '4:18 AM');
insert into MOCK_DATA (id, first_name, last_name, email, gender, ip_address, drug_company, stock_industry, timee) values (98, 'Edmon', 'Grimble', 'egrimble2p@geocities.com', 'Male', '241.22.98.212', 'Rite Aid Corporation', 'Publishing', '2:29 AM');
insert into MOCK_DATA (id, first_name, last_name, email, gender, ip_address, drug_company, stock_industry, timee) values (99, 'Siward', 'O''Regan', 'soregan2q@imageshack.us', 'Male', '171.39.203.23', 'ALL NATURAL DYNAMICS', 'Real Estate Investment Trusts', '9:02 PM');
insert into MOCK_DATA (id, first_name, last_name, email, gender, ip_address, drug_company, stock_industry, timee) values (100, 'Webster', 'Heinrich', 'wheinrich2r@archive.org', 'Male', '62.193.204.56', 'NCS HealthCare of KY, Inc dba Vangard Labs', 'Major Chemicals', '5:39 PM');
