---
- hosts: all
  become: yes
  vars:
      db_user: dbusername
      db_name: dbname
      db_name2: postgres      
      db_name3: test1      
      db_password: dbpassword
      postgresql_version: 14

  tasks:
   
      - name: Ansible copy file sequence to remote server
        copy:
         owner: postgres
         group: postgres
         src:   sequence.sql
         dest: /var/lib/postgresql/scripts


      - name: Cronjob Entry sequence.sql scripts
        cron:
         name: "### execute sequence.sql scripts"
         user: postgres
         minute: "*"
         hour: "*/5"
         day: "*"
         month: "*"
         weekday: "*"
         job: psql -U postgres -d test1 -a -f /var/lib/postgresql/scripts/sequence.sql        

