---
- hosts: all
  become: yes
  vars:
      db_user: dbusername
      db_name: dbname
      db_name2: postgres      
      db_name3: test1      
      db_password: dbpassword
      postgresql_version: 14

  tasks:


      - name: Ansible copy file .bash_profile to remote server in /var/lib/postgresql/ 
        copy:
         owner: postgres
         group: postgres
         mode:  0664         
         src:  .bash_profile
         dest: /var/lib/postgresql/       








