---
- hosts: all
  become: yes
  vars:
      db_user: dbusername
      db_name: dvdrental
      db_name2: postgres      
      db_name3: test1      
      db_password: dbpassword
      postgresql_version: 14

  tasks:


      - name: Create the database specified in vars
        become: true
        become_user: postgres
        postgresql_db: name={{ db_name }}
            template='template0'
            state=present


      - name: Install unzip  
        shell: apt install -y unzip
        args:
         executable: /bin/bash    


#      - name: createdb dvdrental 
#        become: true
#        become_user: postgres      
#        shell: createdb dvdrental 
#        args:
#         executable: /bin/bash    


      - name: Ansible copy file dvdrental.tar to remote server
        copy:
         owner: postgres
         group: postgres
         src:  dvdrental.tar
         dest: /tmp/

      - name: Ansible copy file dvdrental.sh to remote server
        copy:
         owner: postgres
         group: postgres
         mode:  0777         
         src:  dvdrental.sh
         dest: /var/lib/postgresql/scripts/


#      - name: unzip chmod +x dvdrental use script
#        shell: chmod +x /var/lib/postgresql/scripts/dvdrental.sh
#        args:
#         executable: /bin/bash


#      - name: unzip dvdrental use script
#        become: true
#        become_user: postgres      
#        shell: /var/lib/postgresql/scripts/dvdrental.sh
#        args:
#         executable: /bin/bash

      - name: pg_restore dvdrental.tar 
        become: true
        become_user: postgres      
        shell: pg_restore -U postgres -d dvdrental  /tmp/dvdrental.tar 
        args:
         executable: /bin/bash    



## REFERENCES: 
## https://www.postgresqltutorial.com/load-postgresql-sample-database/
## https://www.youtube.com/watch?v=ctESJSfgkBg&t=57s
## https://www.postgresqltutorial.com/postgresql-sample-database/

