---
    - hosts: all
      become: yes
      vars:
          db_user: dbusername
          db_name: dbname
          db_name2: postgres      
          db_name3: test1      
          db_password: dbpassword
          postgresql_version: 14
    
      tasks:


      - name: Ansible copy file  vacuum_pgstattuple.sql to remote server
        copy:
         owner: postgres
         group: postgres
         src:  vacuum_pgstattuple.sql
         dest: /var/lib/postgresql/scripts   

            
      - name: Cronjob Entry vacuum_pgstattuple.sql scripts
        cron:
         name: "### execute vacuum_pgstattuple.sql scripts"
         user: postgres
         minute: "5"
         hour: "20"
         day: "*"
         month: "*"
         weekday: "*"
         job: psql -U postgres -d postgres -a -f /var/lib/postgresql/scripts/vacuum_pgstattuple.sql   
    
